export const orders = [
  {
    id: 1,
    items: [
      {
        id: 1,
        product_id: 1,
        size: "M",
        color: "Blue",
        selling_price: 20.0,
        stock_type: "in-store",
        billing_store_id: 101,
        fulfilment_store_id: 101,
        remarks: "None",
      },
      {
        id: 2,
        product_id: 2,
        size: "L",
        color: "Black",
        selling_price: 40.0,
        stock_type: "other-store",
        billing_store_id: 101,
        fulfilment_store_id: 102,
        remarks: "Ship from other store",
      },
    ],
    customer_id: 1,
    address_id: 1,
    payment_status: "Completed",
    transaction_id: "TXN123456",
    payment_mode: "Card",
    sale_staff_id: 1,
  },
  {
    id: 2,
    items: [
      {
        id: 3,
        product_id: 3,
        size: "S",
        color: "Red",
        selling_price: 60.0,
        stock_type: "on-demand",
        billing_store_id: 103,
        fulfilment_store_id: 103,
        remarks: "Manufacture on demand",
      },
    ],
    customer_id: 2,
    address_id: 2,
    payment_status: "Pending",
    transaction_id: "TXN123457",
    payment_mode: "Cash",
    sale_staff_id: 2,
  },
  {
    id: 3,
    items: [
      {
        id: 4,
        product_id: 4,
        size: "L",
        color: "White",
        selling_price: 80.0,
        stock_type: "in-store",
        billing_store_id: 101,
        fulfilment_store_id: 101,
        remarks: "Urgent delivery",
      },
      {
        id: 5,
        product_id: 5,
        size: "M",
        color: "Green",
        selling_price: 15.0,
        stock_type: "other-store",
        billing_store_id: 101,
        fulfilment_store_id: 103,
        remarks: "Ship from other store",
      },
    ],
    customer_id: 3,
    address_id: 3,
    payment_status: "Completed",
    transaction_id: "TXN123458",
    payment_mode: "Card",
    sale_staff_id: 3,
  },
];
